// ─── SHARED SIMULATED OPERATIONAL DATASET ─────────────────────────────────────
// Single source of truth for all admin modules.
// Relationships: User → Plan → Payment → Leader → Advisor

export const ADVISORS = ['J. Smith', 'M. Lee', 'S. Johnson', 'K. Torres', 'A. Reyes'];

// ── 10 LEADERS ──────────────────────────────────────────────────────────────────
export const LEADERS_DATA = [
  { id: 'L-001', name: 'Carlos López',    country: 'MX', region: 'LATAM',   status: 'certified',           formation: 'certified',    mentor: 'Global HQ',       directs: 18, network: 142, growth: '+22%', conversion: '74%', compliance: 96, communicationScore: 94, activeSince: '2025-08-15', lastActivity: '1h ago',   volume: '$214,000', cycleEarnings: '$4,820', notes: 'Top LATAM leader. Certified. Consistent network expansion.', violations: 0, performance: 'high' },
  { id: 'L-002', name: 'Ana Silva',       country: 'BR', region: 'LATAM',   status: 'certified',           formation: 'certified',    mentor: 'Global HQ',       directs: 12, network: 89,  growth: '+14%', conversion: '71%', compliance: 91, communicationScore: 88, activeSince: '2025-10-01', lastActivity: '3h ago',   volume: '$112,500', cycleEarnings: '$3,110', notes: 'Strong BR network. Slight dip in communication benchmark Q1.', violations: 1, performance: 'high' },
  { id: 'L-003', name: 'Roberto Díaz',   country: 'CO', region: 'LATAM',   status: 'under_review',        formation: 'in_progress',  mentor: 'Carlos López',    directs: 6,  network: 31,  growth: '-3%',  conversion: '54%', compliance: 65, communicationScore: 58, activeSince: '2026-01-20', lastActivity: '2d ago',   volume: '$38,500',  cycleEarnings: '$480',   notes: 'Communication violations detected in WhatsApp groups. Off-script flagged.', violations: 3, performance: 'medium' },
  { id: 'L-004', name: 'Isabella Moreno',country: 'ES', region: 'Europe',  status: 'active',              formation: 'completed',    mentor: 'Global HQ',       directs: 9,  network: 47,  growth: '+8%',  conversion: '62%', compliance: 83, communicationScore: 79, activeSince: '2025-11-12', lastActivity: '5h ago',   volume: '$58,500',  cycleEarnings: '$1,240', notes: 'EU compliance reviewed. Formation complete. Growing steadily.', violations: 0, performance: 'medium' },
  { id: 'L-005', name: 'Kevin Osei',     country: 'GH', region: 'Africa',  status: 'pending_certification',formation: 'in_progress', mentor: 'Ana Silva',       directs: 4,  network: 16,  growth: '+31%', conversion: '68%', compliance: 78, communicationScore: 73, activeSince: '2026-02-28', lastActivity: '12h ago',  volume: '$18,500',  cycleEarnings: '$0',     notes: 'High growth rate. Awaiting final certification review.', violations: 0, performance: 'medium' },
  { id: 'L-006', name: 'Priya Sharma',   country: 'IN', region: 'Asia',    status: 'paused',              formation: 'completed',    mentor: 'Global HQ',       directs: 7,  network: 34,  growth: '+1%',  conversion: '60%', compliance: 74, communicationScore: 70, activeSince: '2025-12-05', lastActivity: '8d ago',   volume: '$31,000',  cycleEarnings: '$620',   notes: 'Self-paused. Personal circumstances. Reactivation review pending.', violations: 0, performance: 'low' },
  { id: 'L-007', name: 'Marco Bianchi',  country: 'IT', region: 'Europe',  status: 'suspended',           formation: 'completed',    mentor: 'Isabella Moreno', directs: 3,  network: 8,   growth: '-8%',  conversion: '38%', compliance: 30, communicationScore: 22, activeSince: '2025-09-10', lastActivity: '18d ago',  volume: '$9,500',   cycleEarnings: '$0',     notes: 'Suspended — multiple compliance violations. Unauthorized income claims. Escalated to legal.', violations: 7, performance: 'low' },
  { id: 'L-008', name: 'Valentina Cruz', country: 'PE', region: 'LATAM',   status: 'active',              formation: 'completed',    mentor: 'Carlos López',    directs: 5,  network: 22,  growth: '+18%', conversion: '66%', compliance: 88, communicationScore: 85, activeSince: '2026-01-10', lastActivity: '6h ago',   volume: '$44,000',  cycleEarnings: '$920',   notes: 'Strong PE market penetration. Excellent onboarding scores.', violations: 0, performance: 'high' },
  { id: 'L-009', name: 'James Okafor',   country: 'NG', region: 'Africa',  status: 'active',              formation: 'completed',    mentor: 'Ana Silva',       directs: 6,  network: 28,  growth: '+25%', conversion: '70%', compliance: 85, communicationScore: 81, activeSince: '2026-02-01', lastActivity: '4h ago',   volume: '$52,000',  cycleEarnings: '$1,080', notes: 'NG growth leader. Community-driven referral system performing well.', violations: 0, performance: 'high' },
  { id: 'L-010', name: 'Mei Lin Chen',   country: 'TW', region: 'Asia',    status: 'certified',           formation: 'certified',    mentor: 'Global HQ',       directs: 8,  network: 42,  growth: '+16%', conversion: '72%', compliance: 93, communicationScore: 90, activeSince: '2025-09-20', lastActivity: '2h ago',   volume: '$89,000',  cycleEarnings: '$2,140', notes: 'Certified. Strong TW market. High compliance score. Model communicator.', violations: 0, performance: 'high' },
];

// ── 50 PARTICIPANTS ──────────────────────────────────────────────────────────────
// Fields: id, name, email, country, type, leader, line, status, plan, amount,
//         kyc, source, advisor, followUp, registration, lastActivity,
//         referrals, volume, compliance, notes, tags, investmentTotal, cycle,
//         paymentMethod, paymentStatus, paymentOrigin, riskScore
export const PARTICIPANTS_DATA = [
  // ── CARLOS LÓPEZ NETWORK (MX) ────────────────────────────────────────
  { id: 'P-10001', name: 'Alejandro Vega',     email: 'a.vega@hotmail.com',        country: 'MX', type: 'direct',  leader: 'Carlos López',    line: 'Left',  status: 'active',               plan: 'Premium',  amount: 10000, kyc: 'verified',    source: 'Referral',  advisor: 'J. Smith',   followUp: 'converted',   registration: '2026-01-10', lastActivity: '2h ago',  referrals: 5, volume: '$21,000', compliance: 95, notes: 'Top direct recruit. Referred 5 members within first month.', tags: ['VIP', 'Fast Starter'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'BBVA Wire — MX ****8821', riskScore: 8 },
  { id: 'P-10002', name: 'Laura Gutiérrez',    email: 'lgutierrez@gmail.com',      country: 'MX', type: 'direct',  leader: 'Carlos López',    line: 'Right', status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Organic',   advisor: 'M. Lee',     followUp: 'converted',   registration: '2026-01-15', lastActivity: '4h ago',  referrals: 3, volume: '$9,500', compliance: 90, notes: 'Consistent activity. Growing her network in Guadalajara region.', tags: ['Network Builder'], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Visa ****3341 — Banorte MX', riskScore: 11 },
  { id: 'P-10003', name: 'Miguel Hernández',   email: 'mhernandez@outlook.com',    country: 'MX', type: 'network', leader: 'Carlos López',    line: 'Left',  status: 'active',               plan: 'Standard', amount: 5000,  kyc: 'verified',    source: 'Referral',  advisor: 'J. Smith',   followUp: 'converted',   registration: '2026-02-01', lastActivity: '1d ago',  referrals: 2, volume: '$7,000', compliance: 88, notes: 'Referred by Alejandro Vega. Reliable payment record.', tags: [], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'HSBC Wire — MX ****5530', riskScore: 14 },
  { id: 'P-10004', name: 'Fernanda Ríos',      email: 'fernanda.rios@gmail.com',   country: 'MX', type: 'network', leader: 'Carlos López',    line: 'Right', status: 'active',               plan: 'Starter',  amount: 500,   kyc: 'verified',    source: 'Campaign',  advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-02-14', lastActivity: '3h ago',  referrals: 1, volume: '$1,500', compliance: 82, notes: 'Campaign-sourced. First investment completed. Progressing.', tags: [], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'MC ****7712 — Santander MX', riskScore: 16 },
  { id: 'P-10005', name: 'Jorge Castillo',     email: 'jcastillo@yahoo.com.mx',    country: 'MX', type: 'network', leader: 'Carlos López',    line: 'Left',  status: 'pending_verification', plan: 'Basic',    amount: 1000,  kyc: 'pending',     source: 'Organic',   advisor: 'J. Smith',   followUp: 'contacted',   registration: '2026-03-20', lastActivity: '5d ago',  referrals: 0, volume: '$1,000', compliance: 55, notes: 'KYC documents submitted. Awaiting identity verification.', tags: ['Needs Follow-up'], cycle: 'Ineligible', paymentMethod: 'Cash', paymentStatus: 'pending',        paymentOrigin: 'Cash Deposit — CDMX Agent', riskScore: 48 },
  { id: 'P-10006', name: 'Sofía Morales',      email: 'sofia.morales@proton.me',   country: 'MX', type: 'direct',  leader: 'Carlos López',    line: 'Right', status: 'active',               plan: 'Premium',  amount: 10000, kyc: 'verified',    source: 'Social',    advisor: 'A. Reyes',   followUp: 'converted',   registration: '2026-01-28', lastActivity: '5h ago',  referrals: 4, volume: '$18,000', compliance: 93, notes: 'Instagram referral. High engagement. Second investment pending.', tags: ['VIP'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'Citibanamex Wire — MX ****6612', riskScore: 9 },
  { id: 'P-10007', name: 'Raúl Espinoza',      email: 'r.espinoza@gmail.com',      country: 'MX', type: 'network', leader: 'Carlos López',    line: 'Left',  status: 'inactive',             plan: 'Starter',  amount: 500,   kyc: 'verified',    source: 'Referral',  advisor: 'M. Lee',     followUp: 'inactive',    registration: '2025-12-10', lastActivity: '30d ago', referrals: 0, volume: '$500', compliance: 38, notes: 'No activity since January. Dormancy protocol triggered.', tags: ['Dormant'], cycle: 'Suspended', paymentMethod: 'Cash', paymentStatus: 'verified',     paymentOrigin: 'Cash — Monterrey Agent', riskScore: 35 },
  { id: 'P-10008', name: 'Patricia Núñez',     email: 'p.nunez@hotmail.com',       country: 'MX', type: 'network', leader: 'Carlos López',    line: 'Right', status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Campaign',  advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-02-22', lastActivity: '6h ago',  referrals: 2, volume: '$6,500', compliance: 85, notes: 'Facebook campaign lead. Active and consistent.', tags: [], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Amex ****4418 — MX Bank', riskScore: 12 },
  { id: 'P-10009', name: 'Daniel Flores',      email: 'dflores.mx@gmail.com',      country: 'MX', type: 'network', leader: 'Carlos López',    line: 'Left',  status: 'under_review',         plan: 'Standard', amount: 5000,  kyc: 'under_review',source: 'Referral',  advisor: 'S. Johnson', followUp: 'in_progress', registration: '2026-03-05', lastActivity: '7d ago',  referrals: 0, volume: '$5,000', compliance: 62, notes: 'Payment origin flagged. Source inconsistency under compliance review.', tags: ['Fraud Flag'], cycle: 'On Hold', paymentMethod: 'Transfer', paymentStatus: 'under_review',   paymentOrigin: 'Unknown Origin — SPEI MX ****0011', riskScore: 74 },
  { id: 'P-10010', name: 'Claudia Reyes',      email: 'creyes.mex@yahoo.com',      country: 'MX', type: 'direct',  leader: 'Carlos López',    line: 'Right', status: 'active',               plan: 'Elite',    amount: 25000, kyc: 'verified',    source: 'Organic',   advisor: 'A. Reyes',   followUp: 'converted',   registration: '2025-11-15', lastActivity: '2h ago',  referrals: 7, volume: '$42,000', compliance: 97, notes: 'Elite tier. Top network volume generator. Certified communicator.', tags: ['VIP', 'Elite'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'Banamex Wire — MX ****9900', riskScore: 5 },

  // ── ANA SILVA NETWORK (BR) ───────────────────────────────────────────
  { id: 'P-10011', name: 'Lucas Oliveira',     email: 'lucas.oliveira@gmail.com',  country: 'BR', type: 'direct',  leader: 'Ana Silva',       line: 'Left',  status: 'active',               plan: 'Premium',  amount: 10000, kyc: 'verified',    source: 'Referral',  advisor: 'M. Lee',     followUp: 'converted',   registration: '2026-01-20', lastActivity: '1h ago',  referrals: 6, volume: '$28,000', compliance: 94, notes: 'Strong BR direct. Top referral count in February.', tags: ['VIP', 'Fast Starter'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'Itaú Wire — BR ****4420', riskScore: 7 },
  { id: 'P-10012', name: 'Gabriela Santos',    email: 'g.santos@uol.com.br',       country: 'BR', type: 'direct',  leader: 'Ana Silva',       line: 'Right', status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Social',    advisor: 'J. Smith',   followUp: 'converted',   registration: '2026-02-05', lastActivity: '3h ago',  referrals: 2, volume: '$8,000', compliance: 87, notes: 'Social media recruit via LinkedIn. Consistent payments.', tags: ['Network Builder'], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Visa ****8820 — Bradesco BR', riskScore: 13 },
  { id: 'P-10013', name: 'Rafael Costa',       email: 'rafaelcosta@terra.com.br',  country: 'BR', type: 'network', leader: 'Ana Silva',       line: 'Left',  status: 'active',               plan: 'Standard', amount: 5000,  kyc: 'verified',    source: 'Campaign',  advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-01-30', lastActivity: '8h ago',  referrals: 3, volume: '$12,500', compliance: 91, notes: 'Campaign conversion. Referred 3 members in first 45 days.', tags: [], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'Bradesco Wire — BR ****6614', riskScore: 10 },
  { id: 'P-10014', name: 'Mariana Pereira',    email: 'm.pereira@gmail.com',       country: 'BR', type: 'network', leader: 'Ana Silva',       line: 'Right', status: 'active',               plan: 'Basic',    amount: 1000,  kyc: 'verified',    source: 'Organic',   advisor: 'M. Lee',     followUp: 'converted',   registration: '2026-02-18', lastActivity: '5h ago',  referrals: 1, volume: '$2,500', compliance: 84, notes: 'Organic signup. Showed interest in upgrade to Growth plan.', tags: [], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'MC ****3391 — Nubank BR', riskScore: 17 },
  { id: 'P-10015', name: 'Thiago Almeida',     email: 'thiago.alm@hotmail.com',    country: 'BR', type: 'network', leader: 'Ana Silva',       line: 'Left',  status: 'pending_verification', plan: 'Growth',   amount: 2500,  kyc: 'pending',     source: 'Referral',  advisor: 'S. Johnson', followUp: 'contacted',   registration: '2026-03-15', lastActivity: '4d ago',  referrals: 0, volume: '$2,500', compliance: 52, notes: 'KYC in queue. Referred by Lucas Oliveira. Awaiting document approval.', tags: ['Needs Follow-up'], cycle: 'Ineligible', paymentMethod: 'Transfer', paymentStatus: 'pending',        paymentOrigin: 'Caixa Wire — BR ****7720', riskScore: 42 },
  { id: 'P-10016', name: 'Beatriz Rocha',      email: 'beatriz.rocha@gmail.com',   country: 'BR', type: 'direct',  leader: 'Ana Silva',       line: 'Right', status: 'active',               plan: 'Elite',    amount: 25000, kyc: 'verified',    source: 'Organic',   advisor: 'A. Reyes',   followUp: 'converted',   registration: '2025-12-01', lastActivity: '3h ago',  referrals: 8, volume: '$51,000', compliance: 96, notes: 'Elite member. Highest volume contributor in BR. Strategic partner.', tags: ['VIP', 'Elite'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'Santander Wire — BR ****2233', riskScore: 4 },
  { id: 'P-10017', name: 'Eduardo Lima',       email: 'edu.lima@uol.com.br',       country: 'BR', type: 'network', leader: 'Ana Silva',       line: 'Left',  status: 'active',               plan: 'Starter',  amount: 500,   kyc: 'verified',    source: 'Campaign',  advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-03-01', lastActivity: '1d ago',  referrals: 0, volume: '$500', compliance: 79, notes: 'New starter. Good initial engagement. Follow-up scheduled.', tags: [], cycle: 'Eligible', paymentMethod: 'Cash', paymentStatus: 'verified',     paymentOrigin: 'Cash — São Paulo Agent', riskScore: 22 },
  { id: 'P-10018', name: 'Camila Ferreira',    email: 'camilaf@terra.com.br',      country: 'BR', type: 'network', leader: 'Ana Silva',       line: 'Right', status: 'blocked',              plan: 'Standard', amount: 5000,  kyc: 'rejected',    source: 'Referral',  advisor: 'S. Johnson', followUp: 'inactive',    registration: '2026-02-10', lastActivity: '21d ago', referrals: 0, volume: '$0', compliance: 12, notes: 'Blocked — KYC document fraud detected. Third-party identity suspected. Escalated.', tags: ['Blocked', 'Fraud Flag'], cycle: 'Blocked', paymentMethod: 'Transfer', paymentStatus: 'flagged',        paymentOrigin: 'Unknown IBAN — BR ****0000', riskScore: 95 },

  // ── ROBERTO DÍAZ NETWORK (CO) ────────────────────────────────────────
  { id: 'P-10019', name: 'Andrés Vargas',      email: 'avargas.co@gmail.com',      country: 'CO', type: 'direct',  leader: 'Roberto Díaz',   line: 'Left',  status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Referral',  advisor: 'J. Smith',   followUp: 'converted',   registration: '2026-02-05', lastActivity: '6h ago',  referrals: 2, volume: '$6,000', compliance: 80, notes: 'Referred by Roberto Díaz directly. Progressing well.', tags: [], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'Bancolombia Wire — CO ****3340', riskScore: 18 },
  { id: 'P-10020', name: 'Natalia Giraldo',    email: 'n.giraldo@hotmail.com',     country: 'CO', type: 'direct',  leader: 'Roberto Díaz',   line: 'Right', status: 'active',               plan: 'Standard', amount: 5000,  kyc: 'verified',    source: 'Social',    advisor: 'M. Lee',     followUp: 'converted',   registration: '2026-01-25', lastActivity: '1d ago',  referrals: 3, volume: '$11,000', compliance: 83, notes: 'LinkedIn social recruit. Regular activity. Upgrading plan.', tags: ['Network Builder'], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Visa ****6621 — Davivienda CO', riskScore: 15 },
  { id: 'P-10021', name: 'Diego Ospina',       email: 'dospina@yahoo.com',         country: 'CO', type: 'network', leader: 'Roberto Díaz',   line: 'Left',  status: 'under_review',         plan: 'Premium',  amount: 10000, kyc: 'under_review',source: 'Campaign',  advisor: 'S. Johnson', followUp: 'in_progress', registration: '2026-03-08', lastActivity: '6d ago',  referrals: 0, volume: '$10,000', compliance: 58, notes: 'High-value transaction under AML review. Origin documentation incomplete.', tags: ['Fraud Flag', 'High Risk'], cycle: 'On Hold', paymentMethod: 'Transfer', paymentStatus: 'under_review',   paymentOrigin: 'Unknown Origin — CO IBAN', riskScore: 81 },
  { id: 'P-10022', name: 'Paola Restrepo',     email: 'prestrepo@gmail.com',       country: 'CO', type: 'network', leader: 'Roberto Díaz',   line: 'Right', status: 'active',               plan: 'Basic',    amount: 1000,  kyc: 'verified',    source: 'Organic',   advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-02-20', lastActivity: '8h ago',  referrals: 1, volume: '$1,500', compliance: 77, notes: 'Organic signup. Steady progress. Interested in Growth plan.', tags: [], cycle: 'Eligible', paymentMethod: 'Cash', paymentStatus: 'verified',     paymentOrigin: 'Cash — Bogotá Agent', riskScore: 28 },
  { id: 'P-10023', name: 'Sebastián Mora',     email: 's.mora.co@outlook.com',     country: 'CO', type: 'network', leader: 'Roberto Díaz',   line: 'Left',  status: 'paused',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Referral',  advisor: 'A. Reyes',   followUp: 'inactive',    registration: '2026-01-12', lastActivity: '14d ago', referrals: 1, volume: '$3,500', compliance: 64, notes: 'Self-paused. Awaiting personal situation resolution. Recontact scheduled.', tags: ['Dormant'], cycle: 'Suspended', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'Bancolombia Wire — CO ****1199', riskScore: 31 },
  { id: 'P-10024', name: 'Valentina Torres',   email: 'vtorres.biz@gmail.com',     country: 'CO', type: 'direct',  leader: 'Roberto Díaz',   line: 'Right', status: 'active',               plan: 'Starter',  amount: 500,   kyc: 'verified',    source: 'Social',    advisor: 'J. Smith',   followUp: 'in_progress', registration: '2026-03-25', lastActivity: '2d ago',  referrals: 0, volume: '$500', compliance: 72, notes: 'New social media signup. Onboarding in progress.', tags: [], cycle: 'Ineligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'MC ****8831 — Nequi CO', riskScore: 20 },

  // ── ISABELLA MORENO NETWORK (ES) ─────────────────────────────────────
  { id: 'P-10025', name: 'Carlos Sánchez',     email: 'c.sanchez.es@gmail.com',    country: 'ES', type: 'direct',  leader: 'Isabella Moreno', line: 'Left',  status: 'active',               plan: 'Premium',  amount: 10000, kyc: 'verified',    source: 'Referral',  advisor: 'M. Lee',     followUp: 'converted',   registration: '2026-01-05', lastActivity: '2h ago',  referrals: 4, volume: '$22,000', compliance: 92, notes: 'EU compliant. Top ES recruiter. Strong professional network.', tags: ['VIP'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'SEPA Transfer — ES IBAN ****8841', riskScore: 9 },
  { id: 'P-10026', name: 'Elena Martínez',     email: 'elena.m@hotmail.es',        country: 'ES', type: 'network', leader: 'Isabella Moreno', line: 'Right', status: 'active',               plan: 'Standard', amount: 5000,  kyc: 'verified',    source: 'Organic',   advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-02-10', lastActivity: '1d ago',  referrals: 2, volume: '$9,000', compliance: 86, notes: 'Strong engagement post-onboarding. Network expanding in Madrid.', tags: [], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Visa ****2290 — Santander ES', riskScore: 13 },
  { id: 'P-10027', name: 'Pablo García',       email: 'pablo.garcia@gmail.com',    country: 'ES', type: 'network', leader: 'Isabella Moreno', line: 'Left',  status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Campaign',  advisor: 'S. Johnson', followUp: 'converted',   registration: '2026-02-28', lastActivity: '7h ago',  referrals: 1, volume: '$5,000', compliance: 81, notes: 'Google Ads campaign conversion. Regular payments.', tags: [], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'SEPA — ES ****3310', riskScore: 16 },
  { id: 'P-10028', name: 'Ana Fernández',      email: 'anafernandez.eu@gmail.com', country: 'ES', type: 'network', leader: 'Isabella Moreno', line: 'Right', status: 'pending_verification', plan: 'Basic',    amount: 1000,  kyc: 'pending',     source: 'Referral',  advisor: 'J. Smith',   followUp: 'contacted',   registration: '2026-03-22', lastActivity: '3d ago',  referrals: 0, volume: '$1,000', compliance: 53, notes: 'Referred by Carlos Sánchez. KYC queued for EU compliance check.', tags: ['Needs Follow-up'], cycle: 'Ineligible', paymentMethod: 'Card', paymentStatus: 'pending',        paymentOrigin: 'MC ****5510 — CaixaBank ES', riskScore: 39 },
  { id: 'P-10029', name: 'Javier López',       email: 'javi.lopez@outlook.es',     country: 'ES', type: 'direct',  leader: 'Isabella Moreno', line: 'Left',  status: 'active',               plan: 'Elite',    amount: 25000, kyc: 'verified',    source: 'Organic',   advisor: 'A. Reyes',   followUp: 'converted',   registration: '2025-12-15', lastActivity: '4h ago',  referrals: 5, volume: '$38,000', compliance: 95, notes: 'Elite ES member. Business background. Strategic network ambassador.', tags: ['VIP', 'Elite'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'SEPA — BBVA ES ****7744', riskScore: 6 },

  // ── KEVIN OSEI NETWORK (GH) ──────────────────────────────────────────
  { id: 'P-10030', name: 'Kwame Asante',       email: 'kwame.asante@gmail.com',    country: 'GH', type: 'direct',  leader: 'Kevin Osei',      line: 'Left',  status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Referral',  advisor: 'M. Lee',     followUp: 'converted',   registration: '2026-03-01', lastActivity: '4h ago',  referrals: 2, volume: '$6,000', compliance: 83, notes: 'Community leader in Accra. Referred 2 trusted contacts.', tags: ['Community'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'GH Mobile Money — MTN ****2281', riskScore: 19 },
  { id: 'P-10031', name: 'Abena Mensah',       email: 'abena.mensah@yahoo.com',    country: 'GH', type: 'network', leader: 'Kevin Osei',      line: 'Right', status: 'active',               plan: 'Starter',  amount: 500,   kyc: 'verified',    source: 'Social',    advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-03-10', lastActivity: '1d ago',  referrals: 0, volume: '$500', compliance: 75, notes: 'Social media signup. First activation confirmed.', tags: [], cycle: 'Eligible', paymentMethod: 'Cash', paymentStatus: 'verified',     paymentOrigin: 'Cash — Accra Network Agent', riskScore: 24 },
  { id: 'P-10032', name: 'Yaw Boateng',        email: 'yaw.boateng@gmail.com',     country: 'GH', type: 'network', leader: 'Kevin Osei',      line: 'Left',  status: 'pending_verification', plan: 'Basic',    amount: 1000,  kyc: 'pending',     source: 'Campaign',  advisor: 'S. Johnson', followUp: 'contacted',   registration: '2026-03-28', lastActivity: '5d ago',  referrals: 0, volume: '$1,000', compliance: 48, notes: 'KYC pending. Cash deposit route. Agent confirmation awaited.', tags: ['Needs Follow-up'], cycle: 'Ineligible', paymentMethod: 'Cash', paymentStatus: 'pending',        paymentOrigin: 'Cash — Kumasi Agent', riskScore: 52 },
  { id: 'P-10033', name: 'Efua Adjei',         email: 'efua.adjei@gmail.com',      country: 'GH', type: 'direct',  leader: 'Kevin Osei',      line: 'Right', status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Organic',   advisor: 'A. Reyes',   followUp: 'converted',   registration: '2026-02-18', lastActivity: '6h ago',  referrals: 3, volume: '$8,000', compliance: 88, notes: 'Organic growth. Strong community connections in GH market.', tags: ['Network Builder'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'GH Mobile — Vodafone ****8840', riskScore: 15 },

  // ── PRIYA SHARMA NETWORK (IN) ────────────────────────────────────────
  { id: 'P-10034', name: 'Arjun Patel',        email: 'arjun.patel@gmail.com',     country: 'IN', type: 'direct',  leader: 'Priya Sharma',    line: 'Left',  status: 'active',               plan: 'Standard', amount: 5000,  kyc: 'verified',    source: 'Referral',  advisor: 'J. Smith',   followUp: 'converted',   registration: '2026-01-18', lastActivity: '8h ago',  referrals: 3, volume: '$10,500', compliance: 86, notes: 'Tech sector professional. Referred 3 colleagues. Reliable.', tags: [], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'NEFT — HDFC Bank IN ****5520', riskScore: 12 },
  { id: 'P-10035', name: 'Priya Nair',         email: 'priya.nair.in@gmail.com',   country: 'IN', type: 'network', leader: 'Priya Sharma',    line: 'Right', status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Social',    advisor: 'M. Lee',     followUp: 'converted',   registration: '2026-02-14', lastActivity: '2d ago',  referrals: 1, volume: '$3,500', compliance: 80, notes: 'Social network recruit. Progressing with monthly contributions.', tags: [], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Visa ****3390 — SBI IN', riskScore: 18 },
  { id: 'P-10036', name: 'Rahul Gupta',        email: 'rahulg@rediffmail.com',     country: 'IN', type: 'network', leader: 'Priya Sharma',    line: 'Left',  status: 'paused',               plan: 'Starter',  amount: 500,   kyc: 'verified',    source: 'Organic',   advisor: 'K. Torres',  followUp: 'inactive',    registration: '2025-12-20', lastActivity: '22d ago', referrals: 0, volume: '$500', compliance: 43, notes: 'Paused due to account review request. Advisor follow-up pending.', tags: ['Dormant'], cycle: 'Suspended', paymentMethod: 'Cash', paymentStatus: 'verified',     paymentOrigin: 'Cash — Mumbai Agent', riskScore: 34 },
  { id: 'P-10037', name: 'Ananya Singh',       email: 'ananya.singh@gmail.com',    country: 'IN', type: 'direct',  leader: 'Priya Sharma',    line: 'Right', status: 'active',               plan: 'Premium',  amount: 10000, kyc: 'verified',    source: 'Referral',  advisor: 'S. Johnson', followUp: 'converted',   registration: '2026-01-30', lastActivity: '5h ago',  referrals: 4, volume: '$19,000', compliance: 91, notes: 'Premium IN recruit. Expanding network rapidly in Bangalore.', tags: ['VIP'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'RTGS — ICICI Bank IN ****7711', riskScore: 8 },

  // ── JAMES OKAFOR NETWORK (NG) ────────────────────────────────────────
  { id: 'P-10038', name: 'Chidi Nwosu',        email: 'chidi.nwosu@gmail.com',     country: 'NG', type: 'direct',  leader: 'James Okafor',    line: 'Left',  status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Referral',  advisor: 'J. Smith',   followUp: 'converted',   registration: '2026-02-08', lastActivity: '3h ago',  referrals: 3, volume: '$7,500', compliance: 85, notes: 'Lagos-based. Strong referral activity. Trusted community member.', tags: ['Network Builder'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'UBA Bank Wire — NG ****4412', riskScore: 16 },
  { id: 'P-10039', name: 'Ngozi Eze',          email: 'ngozi.eze@yahoo.com',       country: 'NG', type: 'network', leader: 'James Okafor',    line: 'Right', status: 'active',               plan: 'Standard', amount: 5000,  kyc: 'verified',    source: 'Social',    advisor: 'A. Reyes',   followUp: 'converted',   registration: '2026-01-22', lastActivity: '1d ago',  referrals: 2, volume: '$9,000', compliance: 83, notes: 'Whatsapp referral. Consistent monthly activity.', tags: [], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Visa ****2211 — First Bank NG', riskScore: 14 },
  { id: 'P-10040', name: 'Emeka Obi',          email: 'emeka.obi@gmail.com',       country: 'NG', type: 'network', leader: 'James Okafor',    line: 'Left',  status: 'pending_verification', plan: 'Basic',    amount: 1000,  kyc: 'pending',     source: 'Campaign',  advisor: 'M. Lee',     followUp: 'contacted',   registration: '2026-03-18', lastActivity: '6d ago',  referrals: 0, volume: '$1,000', compliance: 50, notes: 'KYC queue. Submitted documents, awaiting processing.', tags: ['Needs Follow-up'], cycle: 'Ineligible', paymentMethod: 'Cash', paymentStatus: 'pending',        paymentOrigin: 'Cash — Abuja Agent', riskScore: 44 },
  { id: 'P-10041', name: 'Amaka Onyekachi',    email: 'amaka.o@gmail.com',         country: 'NG', type: 'direct',  leader: 'James Okafor',    line: 'Right', status: 'active',               plan: 'Premium',  amount: 10000, kyc: 'verified',    source: 'Organic',   advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-02-20', lastActivity: '7h ago',  referrals: 4, volume: '$21,000', compliance: 89, notes: 'Premium NG recruit. Business network background. High volume.', tags: ['VIP'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'Zenith Bank Wire — NG ****8820', riskScore: 10 },

  // ── MEI LIN CHEN NETWORK (TW) ────────────────────────────────────────
  { id: 'P-10042', name: 'Wei-Ting Huang',     email: 'weiting.h@gmail.com',       country: 'TW', type: 'direct',  leader: 'Mei Lin Chen',    line: 'Left',  status: 'active',               plan: 'Elite',    amount: 25000, kyc: 'verified',    source: 'Referral',  advisor: 'J. Smith',   followUp: 'converted',   registration: '2025-11-20', lastActivity: '2h ago',  referrals: 8, volume: '$48,000', compliance: 97, notes: 'Top TW performer. Elite tier. Highly connected business network.', tags: ['VIP', 'Elite'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'SWIFT — Cathay Bank TW ****9901', riskScore: 5 },
  { id: 'P-10043', name: 'Shu-Fen Lin',        email: 'shufen.lin@gmail.com',      country: 'TW', type: 'network', leader: 'Mei Lin Chen',    line: 'Right', status: 'active',               plan: 'Premium',  amount: 10000, kyc: 'verified',    source: 'Social',    advisor: 'M. Lee',     followUp: 'converted',   registration: '2026-01-08', lastActivity: '4h ago',  referrals: 3, volume: '$18,000', compliance: 93, notes: 'Professional network recruiter. LinkedIn sourced.', tags: ['Network Builder'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'SWIFT — Fubon Bank TW ****3319', riskScore: 8 },
  { id: 'P-10044', name: 'Jun-Yi Chang',       email: 'junyi.chang@gmail.com',     country: 'TW', type: 'network', leader: 'Mei Lin Chen',    line: 'Left',  status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Campaign',  advisor: 'K. Torres',  followUp: 'converted',   registration: '2026-02-12', lastActivity: '1d ago',  referrals: 1, volume: '$4,500', compliance: 88, notes: 'Campaign ad conversion. Regular payments. Good engagement.', tags: [], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Visa ****7730 — CTBC TW', riskScore: 14 },

  // ── VALENTINA CRUZ NETWORK (PE) ──────────────────────────────────────
  { id: 'P-10045', name: 'Fernando Mendoza',   email: 'f.mendoza.pe@gmail.com',    country: 'PE', type: 'direct',  leader: 'Valentina Cruz',  line: 'Left',  status: 'active',               plan: 'Growth',   amount: 2500,  kyc: 'verified',    source: 'Referral',  advisor: 'S. Johnson', followUp: 'converted',   registration: '2026-01-22', lastActivity: '5h ago',  referrals: 2, volume: '$7,000', compliance: 87, notes: 'Lima market leader. Referred 2 quality contacts.', tags: ['Network Builder'], cycle: 'Eligible', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'BCP Wire — PE ****6610', riskScore: 16 },
  { id: 'P-10046', name: 'Rosa Quispe',        email: 'rosa.quispe@hotmail.com',   country: 'PE', type: 'network', leader: 'Valentina Cruz',  line: 'Right', status: 'active',               plan: 'Standard', amount: 5000,  kyc: 'verified',    source: 'Organic',   advisor: 'A. Reyes',   followUp: 'converted',   registration: '2026-02-08', lastActivity: '8h ago',  referrals: 1, volume: '$6,000', compliance: 82, notes: 'Organic recruit. Business owner. Stable performer.', tags: [], cycle: 'Eligible', paymentMethod: 'Card', paymentStatus: 'verified',     paymentOrigin: 'Visa ****4422 — Interbank PE', riskScore: 18 },
  { id: 'P-10047', name: 'Luis Condori',       email: 'l.condori@gmail.com',       country: 'PE', type: 'network', leader: 'Valentina Cruz',  line: 'Left',  status: 'active',               plan: 'Basic',    amount: 1000,  kyc: 'verified',    source: 'Social',    advisor: 'J. Smith',   followUp: 'in_progress', registration: '2026-03-12', lastActivity: '2d ago',  referrals: 0, volume: '$1,000', compliance: 74, notes: 'Social media signup. Onboarding completing. Follow-up needed.', tags: [], cycle: 'Eligible', paymentMethod: 'Cash', paymentStatus: 'verified',     paymentOrigin: 'Cash — Arequipa Agent', riskScore: 27 },

  // ── MARCO BIANCHI NETWORK (IT) — suspended leader, network still active ──
  { id: 'P-10048', name: 'Giulia Rossi',       email: 'giulia.rossi@gmail.com',    country: 'IT', type: 'network', leader: 'Marco Bianchi',   line: 'Left',  status: 'under_review',         plan: 'Growth',   amount: 2500,  kyc: 'under_review',source: 'Referral',  advisor: 'M. Lee',     followUp: 'in_progress', registration: '2026-02-14', lastActivity: '10d ago', referrals: 0, volume: '$2,500', compliance: 55, notes: 'Leader suspended. Participant under reassignment review. Communication audit pending.', tags: ['High Risk'], cycle: 'On Hold', paymentMethod: 'Transfer', paymentStatus: 'under_review',   paymentOrigin: 'SEPA — IT IBAN ****8811', riskScore: 68 },
  { id: 'P-10049', name: 'Marco Esposito',     email: 'm.esposito@libero.it',      country: 'IT', type: 'network', leader: 'Marco Bianchi',   line: 'Right', status: 'under_review',         plan: 'Starter',  amount: 500,   kyc: 'under_review',source: 'Referral',  advisor: 'S. Johnson', followUp: 'in_progress', registration: '2026-02-20', lastActivity: '10d ago', referrals: 0, volume: '$500', compliance: 51, notes: 'Exposed to compliance violations through leader network. Review required.', tags: ['High Risk'], cycle: 'On Hold', paymentMethod: 'Card', paymentStatus: 'under_review',   paymentOrigin: 'Visa ****1122 — UniCredit IT', riskScore: 71 },
  { id: 'P-10050', name: 'Francesca Bruno',    email: 'fbruno@tiscali.it',         country: 'IT', type: 'direct',  leader: 'Marco Bianchi',   line: 'Left',  status: 'paused',               plan: 'Basic',    amount: 1000,  kyc: 'verified',    source: 'Campaign',  advisor: 'K. Torres',  followUp: 'contacted',   registration: '2026-01-28', lastActivity: '15d ago', referrals: 0, volume: '$1,000', compliance: 60, notes: 'Account paused pending leader reassignment. Will be migrated to Isabella Moreno network.', tags: ['Reassignment Pending'], cycle: 'Suspended', paymentMethod: 'Transfer', paymentStatus: 'verified',     paymentOrigin: 'SEPA — Intesa Sanpaolo IT ****3300', riskScore: 38 },
];

// ── CRM DATA (60 entries = 10 leaders + 50 participants) ──────────────────────
export const CRM_DATA = [
  ...LEADERS_DATA.map(l => ({
    id: l.id, name: l.name, email: `${l.name.toLowerCase().replace(/\s/g,'.')}@network.com`,
    phone: '', country: l.country, source: 'Organic', leader: 'HQ', plan: 'N/A (Leader)',
    status: l.status, kyc: l.status === 'certified' ? 'verified' : l.status === 'suspended' ? 'rejected' : 'verified',
    registration: l.activeSince, lastActivity: l.lastActivity,
    notes: l.notes, tags: [l.performance === 'high' ? 'Top Performer' : l.performance === 'low' ? 'At Risk' : 'Active'],
    investmentTotal: l.volume, cycle: l.status === 'certified' || l.status === 'active' ? 'Eligible' : 'Ineligible',
    advisor: 'HQ Supervisor', followUp: l.status === 'certified' || l.status === 'active' ? 'converted' : l.status === 'suspended' ? 'inactive' : 'in_progress',
  })),
  ...PARTICIPANTS_DATA.map(p => ({
    id: p.id, name: p.name, email: p.email, phone: '', country: p.country,
    source: p.source, leader: p.leader, plan: `${p.plan} — $${p.amount.toLocaleString()}`,
    status: p.status, kyc: p.kyc, registration: p.registration, lastActivity: p.lastActivity,
    notes: p.notes, tags: p.tags, investmentTotal: p.volume, cycle: p.cycle,
    advisor: p.advisor, followUp: p.followUp,
  })),
];

// ── PAYMENTS DATA (one transaction per participant) ────────────────────────────
export const PAYMENTS_DATA = PARTICIPANTS_DATA.map((p, i) => ({
  id: `TXN-${88500 + i}`,
  participant: p.name,
  participantId: p.id,
  country: p.country,
  leader: p.leader,
  amount: p.amount,
  currency: 'USD',
  method: p.paymentMethod,
  origin: p.paymentOrigin,
  destination: ['flagged','blocked'].includes(p.paymentStatus) ? 'Blocked / Pending' : ['pending','under_review'].includes(p.paymentStatus) ? 'Pending Clearance' : 'Platform Account — Internal',
  purpose: `Plan Activation — ${p.plan}`,
  status: p.paymentStatus,
  date: p.registration + ' 10:' + String((i * 7) % 60).padStart(2,'0'),
  reviewedBy: p.paymentStatus === 'verified' ? ADVISORS[i % ADVISORS.length] : '—',
  riskScore: p.riskScore,
  notes: p.notes,
}));

// ── INVESTMENTS DATA ──────────────────────────────────────────────────────────
const PLAN_CATEGORY = { Starter: 'Entry', Basic: 'Starter', Growth: 'Growth', Standard: 'Core', Premium: 'Core', Elite: 'Elite' };
export const INVESTMENTS_DATA = PARTICIPANTS_DATA.map((p, i) => ({
  id: `INV-${6001 + i}`,
  participant: p.name,
  participantId: p.id,
  country: p.country,
  leader: p.leader,
  plan: p.plan,
  category: PLAN_CATEGORY[p.plan] || 'Core',
  amount: p.amount,
  currency: 'USD',
  activation: p.status === 'active' ? 'active' : p.status === 'blocked' ? 'blocked' : p.status === 'paused' ? 'inactive' : 'inactive',
  status: p.paymentStatus === 'verified' && p.status === 'active' ? 'approved'
        : p.paymentStatus === 'flagged' ? 'rejected'
        : p.paymentStatus === 'under_review' ? 'under_compliance'
        : 'pending_review',
  paymentMethod: p.paymentMethod,
  date: p.registration,
  points: p.status === 'active' ? p.amount : 0,
  cycleEligible: p.cycle === 'Eligible',
  notes: p.notes,
  reviewedBy: p.paymentStatus === 'verified' ? ADVISORS[i % ADVISORS.length] : '—',
}));

// ── SUPPORT CASES ─────────────────────────────────────────────────────────────
export const SUPPORT_CASES_DATA = [
  { id: 'CS-5001', title: 'Payment not reflected after transfer — 72h', type: 'payment', participant: 'Jorge Castillo', participantId: 'P-10005', country: 'MX', leader: 'Carlos López', priority: 'critical', status: 'escalated', assigned: 'J. Smith', created: '2026-04-08', lastUpdate: '2h ago', sla: 'BREACHED', age: '5d', notes: 'SPEI transfer not reflected after 72h. Participant requests urgent resolution. Finance team notified.', messages: [{ from: 'J. Smith', text: 'Finance team escalated. Bank confirmation pending.', time: '2026-04-11 09:30' }, { from: 'System', text: 'SLA breach auto-escalation triggered at 72h.', time: '2026-04-11 08:00' }] },
  { id: 'CS-5002', title: 'AML flag — request to review payment origin', type: 'compliance', participant: 'Daniel Flores', participantId: 'P-10009', country: 'MX', leader: 'Carlos López', priority: 'critical', status: 'in_review', assigned: 'S. Johnson', created: '2026-04-06', lastUpdate: '1d ago', sla: 'BREACHED', age: '7d', notes: 'AML engine flagged payment. Participant disputes origin classification. Compliance team reviewing documentation.', messages: [{ from: 'S. Johnson', text: 'Received payment origin documents from participant. Verifying against KYC profile.', time: '2026-04-10 14:00' }, { from: 'Admin', text: 'Escalated to AML compliance officer.', time: '2026-04-08 10:00' }] },
  { id: 'CS-5003', title: 'KYC document rejection — resubmission required', type: 'kyc', participant: 'Thiago Almeida', participantId: 'P-10015', country: 'BR', leader: 'Ana Silva', priority: 'high', status: 'awaiting_participant', assigned: 'M. Lee', created: '2026-04-09', lastUpdate: '18h ago', sla: 'At Risk', age: '4d', notes: 'Automated KYC scanner rejected document — incorrect file format and expired ID. Participant notified via email.', messages: [{ from: 'M. Lee', text: 'Sent resubmission instructions. Waiting on participant response.', time: '2026-04-10 11:00' }] },
  { id: 'CS-5004', title: 'Duplicate registration investigation', type: 'compliance', participant: 'Camila Ferreira', participantId: 'P-10018', country: 'BR', leader: 'Ana Silva', priority: 'critical', status: 'escalated', assigned: 'S. Johnson', created: '2026-04-05', lastUpdate: '2d ago', sla: 'BREACHED', age: '8d', notes: 'Two registrations detected under different emails but same identity documents. Account blocked. AML report submitted.', messages: [{ from: 'S. Johnson', text: 'AML report filed. Legal team notified. Account to remain blocked.', time: '2026-04-08 16:00' }, { from: 'System', text: 'Account blocked automatically. Fraud flag raised.', time: '2026-04-05 17:00' }] },
  { id: 'CS-5005', title: 'High-value payment review — $10,000 threshold', type: 'payment', participant: 'Diego Ospina', participantId: 'P-10021', country: 'CO', leader: 'Roberto Díaz', priority: 'high', status: 'in_review', assigned: 'K. Torres', created: '2026-04-09', lastUpdate: '12h ago', sla: 'At Risk', age: '4d', notes: 'Automatic hold triggered for payment >$5,000. Origin documentation submitted. Manual review required before approval.', messages: [{ from: 'K. Torres', text: 'Documents received. Review in progress. Expected resolution within 48h.', time: '2026-04-11 10:30' }] },
  { id: 'CS-5006', title: 'Account access lost after leader suspension', type: 'technical', participant: 'Giulia Rossi', participantId: 'P-10048', country: 'IT', leader: 'Marco Bianchi', priority: 'high', status: 'assigned', assigned: 'A. Reyes', created: '2026-04-10', lastUpdate: '8h ago', sla: 'OK', age: '3d', notes: 'Participant cannot access dashboard. Leader network suspended. Reassignment to Isabella Moreno network pending.', messages: [{ from: 'A. Reyes', text: 'Reassignment in queue. Participant notified. Access will restore upon migration.', time: '2026-04-11 14:00' }] },
  { id: 'CS-5007', title: 'Leader communication complaint', type: 'compliance', participant: 'Marco Esposito', participantId: 'P-10049', country: 'IT', leader: 'Marco Bianchi', priority: 'medium', status: 'in_review', assigned: 'S. Johnson', created: '2026-04-07', lastUpdate: '3d ago', sla: 'OK', age: '6d', notes: 'Participant reported unauthorized income projections shared by leader in Telegram group. Screenshots submitted to compliance.', messages: [{ from: 'S. Johnson', text: 'Screenshots reviewed. Content confirmed as non-compliant. Added to leader suspension evidence.', time: '2026-04-09 12:00' }] },
  { id: 'CS-5008', title: 'Plan upgrade request — Standard to Elite', type: 'request', participant: 'Carlos Sánchez', participantId: 'P-10025', country: 'ES', leader: 'Isabella Moreno', priority: 'medium', status: 'new', assigned: 'Unassigned', created: '2026-04-12', lastUpdate: '6h ago', sla: 'OK', age: '1d', notes: 'Participant requesting upgrade from Premium to Elite plan. Payment intent confirmed. Finance review pending.', messages: [] },
  { id: 'CS-5009', title: 'Cycle incentive not paid — C-47', type: 'incentive', participant: 'Laura Gutiérrez', participantId: 'P-10002', country: 'MX', leader: 'Carlos López', priority: 'medium', status: 'assigned', assigned: 'J. Smith', created: '2026-04-08', lastUpdate: '2d ago', sla: 'OK', age: '5d', notes: 'Cycle C-47 incentive not reflected in wallet. Cycle engine log shows eligible but payout not triggered.', messages: [{ from: 'J. Smith', text: 'Cycle engine log reviewed. Possible lag in settlement. Escalating to finance.', time: '2026-04-10 15:00' }] },
  { id: 'CS-5010', title: 'Referral credit not applied', type: 'incentive', participant: 'Kwame Asante', participantId: 'P-10030', country: 'GH', leader: 'Kevin Osei', priority: 'low', status: 'resolved', assigned: 'M. Lee', created: '2026-04-03', lastUpdate: '4d ago', sla: 'OK', age: '10d', notes: 'Referral credit missing for two activations. Timing offset identified. Manual credit applied. Participant confirmed.', messages: [{ from: 'M. Lee', text: 'Manual credit applied for both referrals. Participant confirmed receipt.', time: '2026-04-07 11:00' }] },
  { id: 'CS-5011', title: 'Cash deposit receipt not received', type: 'payment', participant: 'Yaw Boateng', participantId: 'P-10032', country: 'GH', leader: 'Kevin Osei', priority: 'high', status: 'new', assigned: 'Unassigned', created: '2026-04-12', lastUpdate: '5h ago', sla: 'OK', age: '1d', notes: 'Cash deposit via Kumasi agent. No receipt confirmation from agent. Participant flagged as unconfirmed.', messages: [] },
  { id: 'CS-5012', title: 'Identity document mismatch — KYC failure', type: 'kyc', participant: 'Ana Fernández', participantId: 'P-10028', country: 'ES', leader: 'Isabella Moreno', priority: 'medium', status: 'awaiting_participant', assigned: 'K. Torres', created: '2026-04-10', lastUpdate: '1d ago', sla: 'OK', age: '3d', notes: 'KYC scanner detected name mismatch between ID document and registration form. Participant requested to resubmit.', messages: [{ from: 'K. Torres', text: 'Participant contacted. Resubmission expected within 48h.', time: '2026-04-11 09:00' }] },
  { id: 'CS-5013', title: 'Leader reassignment request from suspended network', type: 'request', participant: 'Francesca Bruno', participantId: 'P-10050', country: 'IT', leader: 'Marco Bianchi', priority: 'medium', status: 'in_review', assigned: 'A. Reyes', created: '2026-04-08', lastUpdate: '2d ago', sla: 'OK', age: '5d', notes: 'Participant requests reassignment following leader suspension. Migration to Isabella Moreno network approved in principle.', messages: [{ from: 'A. Reyes', text: 'Migration approved. Technical reassignment scheduled for next business day.', time: '2026-04-10 16:00' }] },
  { id: 'CS-5014', title: 'Payment method change request', type: 'request', participant: 'Beatriz Rocha', participantId: 'P-10016', country: 'BR', leader: 'Ana Silva', priority: 'low', status: 'resolved', assigned: 'M. Lee', created: '2026-04-01', lastUpdate: '7d ago', sla: 'OK', age: '12d', notes: 'Participant requested switch from card to bank transfer for future payments. Updated in profile. Confirmed.', messages: [{ from: 'M. Lee', text: 'Payment method updated. Participant confirmed change via email.', time: '2026-04-03 14:00' }] },
  { id: 'CS-5015', title: 'Inactivity alert — dormancy review requested', type: 'account', participant: 'Raúl Espinoza', participantId: 'P-10007', country: 'MX', leader: 'Carlos López', priority: 'low', status: 'closed', assigned: 'J. Smith', created: '2026-03-25', lastUpdate: '10d ago', sla: 'OK', age: '19d', notes: 'Dormancy protocol triggered at 30 days inactivity. Advisor contacted participant. No response. Account marked inactive.', messages: [{ from: 'J. Smith', text: 'Three contact attempts made via email and WhatsApp. No response. Closing case. Account remains inactive.', time: '2026-04-02 11:00' }] },
];