export const TOOLS_TABS = [
  {
    id: "packages",
    label: "Packages",
    // Tab de acceso directo al catálogo real (paywall): ToolsPage lo
    // renderiza como CTA hacia /dashboard/packages.
    linkTo: "/dashboard/packages",
    linkTitle: "Membresías de inversión",
    linkDescription: "Catálogo PACK MINDBLISS con activación por Stripe (tarjeta y crypto).",
  },
  {
    id: "bank-account",
    label: "Bank Account",
    columns: [
      { key: "id", label: "ID", type: "mono" },
      { key: "bank", label: "Bank", type: "strong" },
      { key: "account", label: "Account" },
      { key: "clabe", label: "Clabe", type: "mono" },
      { key: "country", label: "Country" },
      { key: "name", label: "Name Account" },
    ],
    rows: [
      { id: "ID001", bank: "Banco Santander", account: "1234567890", clabe: "014180001234567890", country: "Mexico", name: "Carlos Mendoza" },
      { id: "ID002", bank: "Banco do Brasil", account: "9876543210", clabe: "001180009876543210", country: "Brazil", name: "Ana Silva" },
    ],
  },
  {
    id: "documents",
    label: "Documents",
    columns: [
      { key: "no", label: "No.", type: "mono" },
      { key: "nameEn", label: "Name in English", type: "strong" },
      { key: "nameEs", label: "Name in Spanish" },
      { key: "visibleIn", label: "Visible in", type: "badge" },
      { key: "formats", label: "Accepted Formats" },
      { key: "country", label: "Country Required" },
    ],
    rows: [
      {
        no: "01",
        nameEn: "Identity Card",
        nameEs: "Documento de Identidad",
        visibleIn: { label: "KYC Module", tone: "gray" },
        formats: "PDF, JPG, PNG",
        country: "All Countries",
      },
    ],
  },
  {
    id: "catalogs",
    label: "Catalogs",
    columns: [
      { key: "no", label: "No.", type: "mono" },
      { key: "category", label: "Category Name", type: "strong" },
      { key: "nameEs", label: "Name in Spanish" },
      { key: "nameEn", label: "Name in English" },
      { key: "order", label: "Order" },
      { key: "active", label: "Active", type: "badge" },
    ],
    rows: [
      {
        no: "01",
        category: "System Ranks",
        nameEs: "Rangos Oro",
        nameEn: "Gold Ranks",
        order: "1",
        active: { label: "True", tone: "green" },
      },
    ],
  },
  {
    id: "operator",
    label: "Operator",
    minWidth: 1200,
    columns: [
      { key: "no", label: "No.", type: "mono" },
      { key: "operatorId", label: "Operator ID", type: "mono" },
      { key: "avatar", label: "Profile Picture", type: "avatar" },
      { key: "fullName", label: "Full Name", type: "strong" },
      { key: "username", label: "Username" },
      { key: "nickname", label: "Nickname" },
      { key: "role", label: "Role" },
      { key: "gender", label: "Gender" },
      { key: "birth", label: "Day of Birth" },
      { key: "code", label: "Code", type: "mono" },
      { key: "phone", label: "Phone Number" },
      { key: "email", label: "Email" },
      { key: "joinDate", label: "Join Date" },
      { key: "status", label: "Status", type: "badge" },
    ],
    rows: [
      {
        no: "01",
        operatorId: "OP-492",
        avatar: "JM",
        fullName: "John Miller",
        username: "jmiller_op",
        nickname: "Johnny",
        role: "Supervisor",
        gender: "Male",
        birth: "1992-05-14",
        code: "+1",
        phone: "555-0192",
        email: "j.miller@mindbliss.com",
        joinDate: "2025-01-10",
        status: { label: "Active", tone: "green" },
      },
    ],
  },
  {
    id: "package",
    label: "Packages",
    title: "Packages y Packages VIP",
    columns: [
      { key: "id", label: "ID", type: "mono" },
      { key: "name", label: "Package Name", type: "strong" },
      { key: "type", label: "Type", type: "badge" },
      { key: "price", label: "Price", type: "accent" },
      { key: "features", label: "Features / Limit" },
      { key: "status", label: "Status", type: "badge" },
    ],
    rows: [
      {
        id: "PKG01",
        name: "Starter Pack",
        type: { label: "Standard", tone: "gray" },
        price: "$99.00",
        features: "Basic Access, 10 Profiles",
        status: { label: "Active", tone: "green" },
      },
      {
        id: "PKG02",
        name: "Elite VIP Master",
        type: { label: "VIP", tone: "amber" },
        price: "$1,499.00",
        features: "Unlimited, Priority Node Route",
        status: { label: "Active", tone: "green" },
      },
    ],
  },
  {
    id: "role",
    label: "Role",
    columns: [
      { key: "no", label: "No.", type: "mono" },
      { key: "role", label: "Role", type: "strong" },
      { key: "section", label: "Section" },
      { key: "module", label: "Module" },
    ],
    rows: [{ no: "01", role: "System Admin", section: "All Sections", module: "Full Access Node" }],
  },
  {
    id: "users",
    label: "Users",
    minWidth: 1600,
    columns: [
      { key: "no", label: "No.", type: "mono" },
      { key: "avatar", label: "Profile Picture", type: "avatar" },
      { key: "fullName", label: "Full Name", type: "strong" },
      { key: "username", label: "Username" },
      { key: "birth", label: "Day of Birth" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone Number" },
      { key: "sponsorName", label: "Full Name Sponsor" },
      { key: "sponsor", label: "Sponsor", type: "mono" },
      { key: "joinDate", label: "Join Date" },
      { key: "rank", label: "Rank", type: "accent" },
      { key: "rankDate", label: "Date of achievement of rank" },
      { key: "status", label: "Status", type: "badge" },
      { key: "motive", label: "Motive", type: "mono" },
      { key: "kyc", label: "KYC Approved", type: "badge" },
      { key: "packages", label: "Package purchases" },
    ],
    rows: [
      {
        no: "01",
        avatar: "MR",
        fullName: "Marcus Rivas",
        username: "mrivas_power",
        birth: "1995-11-23",
        email: "marcus.rivas@gmail.com",
        phone: "+52 55219982",
        sponsorName: "Elena Rostova",
        sponsor: "SP-9002",
        joinDate: "2026-02-15",
        rank: "Diamond",
        rankDate: "2026-05-20",
        status: { label: "Active", tone: "green" },
        motive: "None",
        kyc: { label: "Verified", tone: "blue" },
        packages: "Elite VIP Master",
      },
    ],
  },
  { id: "resources", label: "Resources", empty: true },
  {
    id: "system",
    label: "System",
    columns: [
      { key: "no", label: "No.", type: "mono" },
      { key: "parameter", label: "Parameter", type: "strong" },
      { key: "value", label: "Value", type: "mono" },
    ],
    rows: [
      { no: "01", parameter: "maintenance_mode", value: "false" },
      { no: "02", parameter: "max_login_attempts", value: "5" },
    ],
  },
];

export const CREATE_OPTIONS = [
  {
    id: "bank-account",
    label: "New Bank Account",
    fields: [
      { name: "bank", label: "Bank*", type: "select", options: ["Banco Santander", "Banco do Brasil"] },
      { name: "account", label: "Account*", type: "text" },
      { name: "clabe", label: "Clabe*", type: "text" },
      { name: "country", label: "Country*", type: "select", options: ["Mexico", "Brazil"] },
      { name: "name", label: "Name Account", type: "text" },
    ],
  },
  {
    id: "document",
    label: "New Document",
    fields: [
      { name: "nameEn", label: "Name in English*", type: "text" },
      { name: "nameEs", label: "Name in Spanish*", type: "text" },
      { name: "visibleIn", label: "Visible in", type: "select", options: ["KYC Module"] },
      { name: "country", label: "Country", type: "select", options: ["All Countries"] },
      { name: "required", label: "Required", type: "checkbox" },
    ],
  },
  {
    id: "catalog",
    label: "New Catalog",
    fields: [
      { name: "category", label: "Category Name*", type: "select", options: ["System Ranks"] },
      { name: "nameEs", label: "Name in Spanish*", type: "text" },
      { name: "nameEn", label: "Name in English*", type: "text" },
      { name: "order", label: "Order", type: "text" },
      { name: "active", label: "Active", type: "toggle", default: true },
    ],
  },
  {
    id: "operator",
    label: "New Operator",
    wide: true,
    fields: [
      { name: "username", label: "Username*", type: "text", half: true },
      { name: "nickname", label: "Nickname", type: "text", half: true },
      { name: "firstName", label: "First Name*", type: "text", half: true },
      { name: "lastName", label: "Last Name*", type: "text", half: true },
      { name: "gender", label: "Gender*", type: "select", options: ["Male", "Female"], half: true },
      { name: "birth", label: "Day of birth*", type: "date", half: true },
      { name: "email", label: "Email*", type: "text" },
      { name: "role", label: "Role*", type: "select", options: ["Supervisor"], half: true },
      { name: "code", label: "Code*", type: "select", options: ["+1", "+52"], half: true },
      { name: "phone", label: "Phone number*", type: "text", half: true },
      { name: "active", label: "Activate", type: "toggle", default: true, half: true },
    ],
  },
  {
    id: "package",
    label: "New Package",
    fields: [
      { name: "name", label: "Package Name*", type: "text" },
      { name: "type", label: "Type*", type: "select", options: ["Standard", "VIP"] },
      { name: "price", label: "Price*", type: "text" },
      { name: "features", label: "Features / Limit", type: "text" },
      { name: "active", label: "Active", type: "toggle", default: true },
    ],
  },
  {
    id: "role",
    label: "New Module to role",
    fields: [
      { name: "role", label: "Role*", type: "select", options: ["System Admin"] },
      { name: "section", label: "Section*", type: "text" },
      { name: "module", label: "Module*", type: "text" },
    ],
  },
  {
    id: "resources",
    label: "New Media Resources",
    fields: [
      { name: "name", label: "Resource Name*", type: "text" },
      { name: "url", label: "Media URL*", type: "text" },
    ],
  },
];
